- name: Update and upgrade packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install apt packages
  package:
    name:
      - jq
    state: latest

- name: Install snap packages
  ansible.builtin.snap:
    name:
      - yq
    state: present
